pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Build & Test') {
      steps {
        script {
          if (isUnix()) {
            sh 'chmod +x mvnw || true'
            sh './mvnw -B -DskipTests=false clean test'
          } else {
            bat 'mvnw -B -DskipTests=false clean test'
          }
        }
      }
      post {
        always {
          junit 'target/surefire-reports/*.xml'
        }
      }
    }

    stage('Package') {
      steps {
        script {
          if (isUnix()) {
            sh './mvnw -B package'
          } else {
            bat 'mvnw -B package'
          }
        }
      }
    }

    stage('Archive') {
      steps {
        archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
      }
    }
  }
}
